# Generated by Django 6.0.1 on 2026-01-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_order_updated_at_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="brands/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="products/"),
        ),
    ]
