# Generated by Django 4.2.27 on 2026-02-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    # Adjusted dependencies to match local migration filenames
    dependencies = [
        ('store', '0006_phase2_models'),
        ('store', '0007_product_description_product_is_new_product_rating_and_more'),
    ]

    operations = [
    ]
