# Generated by Django 4.2.27 on 2026-02-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_cartitem_coupon_productview_review_savedsearch_and_more'),
        ('store', '0006_emaillog_review_userprofile_reviewimage_paymentlog_and_more'),
        ('store', '0006_emailtemplate_orderanalytics_useranalytics_and_more'),
        ('store', '0007_loginattempt_suspiciousactivity'),
    ]

    operations = [
    ]
