# Generated by Django 4.2.27 on 2026-02-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_product_is_on_sale_searchquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="volume",
            field=models.PositiveIntegerField(
                default=0, help_text="Volume in selected unit, e.g., 5, 18, 20"
            ),
        ),
    ]
