# Generated by Django 4.2.27 on 2026-02-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_product_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
