# Generated by Django 4.2.27 on 2026-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_brand_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
