# Generated by Django 4.2.27 on 2026-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_cart_emaillog_review_userprofile_savedsearch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
