# Generated by Django 4.2.27 on 2026-02-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_review_created_at_alter_review_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Suspicious Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', '-created_at'], name='store_suspi_activit_d7f1a6_idx'), models.Index(fields=['ip_address', '-created_at'], name='store_suspi_ip_addr_2f272e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'success', '-timestamp'], name='store_login_ip_addr_e2f296_idx'), models.Index(fields=['username', '-timestamp'], name='store_login_usernam_5ba9de_idx')],
            },
        ),
    ]
