# Generated by Django 4.2.27 on 2026-02-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0018_alter_category_options_order_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
