# Generated by Django 4.2.27 on 2026-02-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0019_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery (COD)"),
                    ("offline", "Offline (legacy)"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                ],
                default="cod",
                max_length=30,
            ),
        ),
    ]
