# Generated by Django 4.2.27 on 2026-02-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                max_length=30,
            ),
        ),
    ]
