"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import logging
from logging import handlers
import copy as _copy
import ipaddress
from django.template import context as _ctx

# Patch Django template context copy to avoid Python 3.14 incompatibility
def _safe_basecontext_copy(self):
    dup = _ctx.BaseContext.__new__(_ctx.BaseContext)
    dup.__class__ = self.__class__
    dup.__dict__ = _copy.copy(getattr(self, '__dict__', {}))
    dup.dicts = list(getattr(self, 'dicts', []))
    return dup

def _safe_context_copy(self):
    dup = _safe_basecontext_copy(self)
    dup.render_context = _copy.copy(getattr(self, 'render_context', {}))
    return dup

_ctx.BaseContext.__copy__ = _safe_basecontext_copy
_ctx.Context.__copy__ = _safe_context_copy
_ctx.RequestContext.__copy__ = _safe_context_copy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-&pqqh1+_-=p06j)-*50e8afj^$$vr^-hx^5&(n3rg^@r&myzok',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Controlled by environment variable for safe deployment; defaults to True for dev.
DEBUG = os.environ.get("DEBUG", "True").lower() in ("1", "true", "yes", "on")

# Allow local loopback hosts for development; can be overridden via ALLOWED_HOSTS env.
_env_hosts = os.environ.get("ALLOWED_HOSTS")
if _env_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _env_hosts.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = [
        '127.0.0.1',
        'localhost',
        'dailysonphattan',
        'testserver',
    ]

# When DEBUG, allow local LAN IP to avoid DisallowedHost when testing over Wi-Fi/LAN.
if DEBUG:
    try:
        import socket

        def _detect_private_ipv4():
            candidates = set()
            try:
                # Primary outbound interface
                _s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                _s.connect(("8.8.8.8", 80))
                candidates.add(_s.getsockname()[0])
                _s.close()
            except Exception:
                pass
            try:
                for info in socket.getaddrinfo(socket.gethostname(), None):
                    addr = info[4][0]
                    candidates.add(addr)
            except Exception:
                pass
            for addr in candidates:
                try:
                    ip_obj = ipaddress.ip_address(addr)
                    if ip_obj.version == 4 and ip_obj.is_private and not ip_obj.is_loopback:
                        return addr
                except ValueError:
                    continue
            return None

        _lan_ip = _detect_private_ipv4()
        for _host in ('127.0.0.1', 'localhost', _lan_ip):
            if _host and _host not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(_host)
    except Exception:
        # Fallback: ignore if cannot detect; keeps production unaffected
        pass


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'home',
    'store',
    # Note: do NOT register `paint_store` as an app here because it can
    # be a namespace package in some environments and Django will attempt
    # to create an AppConfig for it (causing ImproperlyConfigured errors).
    # Instead we'll import its compatibility shim directly below.
]

# Dev-only helpers (HTTPS runserver_plus, shell_plus, etc.)
if DEBUG:
    INSTALLED_APPS.append('django_extensions')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'store.response_logger_middleware.ResponseLoggerMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
            # Ensure custom filters/tags are always available, even if templates forget to load them.
            'builtins': [
                'store.templatetags.price_extras',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Canonical site URL used for absolute links (sitemaps, JSON-LD). Update for production.
SITE_URL = 'http://127.0.0.1:8888'

# Optional: make STATIC_URL a proper absolute path prefix in templates
if not STATIC_URL.startswith('/'):
    STATIC_URL = '/' + STATIC_URL

# Directory for `collectstatic` (development/prod staging)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'store:profile'
LOGOUT_REDIRECT_URL = 'login'

LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')
LOG_DIR = Path(os.environ.get('LOG_DIR', BASE_DIR / 'logs'))
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Structured logging with rotation; console retained for Docker/stdout
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'structured': {
            'format': '%(asctime)s %(levelname)s %(name)s %(pathname)s:%(lineno)d %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'app.log',
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'structured',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'error.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'level': 'WARNING',
            'formatter': 'structured',
        },
    },
    'root': {
        'handlers': ['console', 'app_file', 'error_file'],
        'level': LOG_LEVEL,
    },
}

# Optional error monitoring (e.g., Sentry). Enable by setting SENTRY_DSN in env.
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except Exception:
    sentry_sdk = None

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
SENTRY_ENV = os.environ.get('SENTRY_ENV', 'production')

if sentry_sdk and SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        send_default_pii=False,
        environment=SENTRY_ENV,
    )

# NOTE: Avoid importing runtime shims during settings import. Doing so can
# create side-effects before Django finishes app setup (e.g., template engine
# registration). If admin compatibility patches are needed, apply them later
# in app-ready hooks or middleware.
