# Generated by Django 6.0.1 on 2026-01-29 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('paint', 'Sơn'), ('waterproof', 'Chống thấm'), ('putty', 'Bột trét'), ('other', 'Khác')], max_length=20)),
                ('unit', models.CharField(choices=[('L', 'Lít'), ('KG', 'Kg')], max_length=2)),
                ('quantity_value', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paint_store.brand')),
            ],
        ),
    ]
