<?php
/**
 * Apply official image map generated by tools/build_official_image_map.ps1.
 *
 * Run:
 *   Get-Content -Raw tools/apply_official_image_map.php | docker exec -i lephat1898-wordpress-1 php
 * Optional:
 *   ... php -- --dry-run
 *   ... php -- --apply-official-title
 *   ... php -- --only-brand=apollo
 */

require '/var/www/html/wp-load.php';

$write_error = static function (string $message): void {
    $line = rtrim($message) . PHP_EOL;
    if (@file_put_contents('php://stderr', $line, FILE_APPEND) === false) {
        echo $line;
    }
};

if (!function_exists('wc_get_product')) {
    $write_error('WooCommerce is not loaded.');
    exit(1);
}

if (!function_exists('wp_generate_attachment_metadata')) {
    require_once ABSPATH . 'wp-admin/includes/image.php';
}
if (!function_exists('wp_insert_attachment')) {
    require_once ABSPATH . 'wp-admin/includes/media.php';
}
if (!function_exists('wp_upload_bits')) {
    require_once ABSPATH . 'wp-admin/includes/file.php';
}

$args = array_values(array_filter((array) ($_SERVER['argv'] ?? []), static function ($v) {
    return is_string($v) && $v !== '';
}));
$dry_run = in_array('--dry-run', $args, true);
$apply_official_title = in_array('--apply-official-title', $args, true);
$only_brand = '';
foreach ($args as $arg_index => $arg_value) {
    $arg_value = (string) $arg_value;
    if (strpos($arg_value, '--only-brand=') === 0) {
        $only_brand = sanitize_title((string) substr($arg_value, 13));
        break;
    }
    if ($arg_value === '--only-brand' && isset($args[$arg_index + 1])) {
        $only_brand = sanitize_title((string) $args[$arg_index + 1]);
        break;
    }
}

$theme_root = (string) get_theme_file_path();
$map_file = wp_normalize_path(trailingslashit($theme_root) . 'data/official_image_map.json');
$fallback_theme_root = '/var/www/html/wp-content/themes/my-theme';
$fallback_map_file = wp_normalize_path(trailingslashit($fallback_theme_root) . 'data/official_image_map.json');
if (!file_exists($map_file) && file_exists($fallback_map_file)) {
    $theme_root = $fallback_theme_root;
    $map_file = $fallback_map_file;
}
if ($map_file === '' || !file_exists($map_file)) {
    $write_error("official image map not found: {$map_file}");
    exit(1);
}

$raw = file_get_contents($map_file);
if (!is_string($raw) || trim($raw) === '') {
    $write_error('official image map is empty.');
    exit(1);
}

$rows = json_decode($raw, true);
if (!is_array($rows)) {
    $write_error('official image map is invalid JSON.');
    exit(1);
}

$import_local_image = static function (string $source_file, string $cache_hint = ''): int {
    if ($source_file === '' || !file_exists($source_file)) {
        return 0;
    }

    $file_hash = md5_file($source_file);
    $cache_key = 'my_theme_official_img_' . md5($source_file . '|' . $file_hash . '|' . $cache_hint);
    $cached_id = (int) get_option($cache_key, 0);
    if ($cached_id > 0 && get_post($cached_id) instanceof WP_Post) {
        return $cached_id;
    }

    $filename = basename($source_file);
    $ext = strtolower((string) pathinfo($filename, PATHINFO_EXTENSION));
    $is_svg = ($ext === 'svg');
    $upload_name = 'official-' . sanitize_title($cache_hint) . '-' . sanitize_file_name($filename);
    $target_file = '';
    if ($is_svg) {
        $uploads = wp_upload_dir();
        if (!is_array($uploads) || !empty($uploads['error']) || empty($uploads['path']) || empty($uploads['basedir'])) {
            return 0;
        }
        $safe_name = sanitize_file_name($upload_name);
        if (substr(strtolower($safe_name), -4) !== '.svg') {
            $safe_name .= '.svg';
        }
        $target_file = wp_normalize_path(trailingslashit((string) $uploads['path']) . $safe_name);
        $target_dir = wp_normalize_path((string) dirname($target_file));
        if (!is_dir($target_dir) && !wp_mkdir_p($target_dir)) {
            return 0;
        }
        if (!@copy($source_file, $target_file)) {
            return 0;
        }
    } else {
        $content = file_get_contents($source_file);
        if (!is_string($content) || $content === '') {
            return 0;
        }
        $bits = wp_upload_bits($upload_name, null, $content);
        if (!empty($bits['error']) || empty($bits['file'])) {
            return 0;
        }
        $target_file = wp_normalize_path((string) $bits['file']);
    }

    $filetype = wp_check_filetype((string) $target_file);
    $mime_type = $is_svg ? 'image/svg+xml' : (string) ($filetype['type'] ?? 'image/jpeg');
    $attach_id = wp_insert_attachment(
        [
            'post_mime_type' => $mime_type,
            'post_title' => 'Official image ' . strtoupper((string) $cache_hint),
            'post_content' => '',
            'post_status' => 'inherit',
        ],
        (string) $target_file
    );

    if (is_wp_error($attach_id) || $attach_id <= 0) {
        return 0;
    }

    if ($is_svg) {
        $uploads = wp_upload_dir();
        $relative_file = '';
        if (is_array($uploads) && !empty($uploads['basedir'])) {
            $relative_file = ltrim(str_replace(wp_normalize_path((string) $uploads['basedir']), '', wp_normalize_path($target_file)), '/');
        }
        if ($relative_file !== '') {
            update_post_meta($attach_id, '_wp_attached_file', $relative_file);
        }
    } else {
        $meta = wp_generate_attachment_metadata($attach_id, (string) $target_file);
        if (is_array($meta)) {
            wp_update_attachment_metadata($attach_id, $meta);
        }
    }

    update_post_meta($attach_id, '_official_image_source_file', $source_file);
    if (is_string($file_hash) && $file_hash !== '') {
        update_post_meta($attach_id, '_official_image_md5', $file_hash);
    }
    update_option($cache_key, (int) $attach_id, false);
    return (int) $attach_id;
};

$looks_like_official_title = static function (string $title): bool {
    $title = trim($title);
    if ($title === '') {
        return false;
    }
    if (mb_strlen($title) < 4 || mb_strlen($title) > 120) {
        return false;
    }
    $noise = [
        'trang chủ',
        'home',
        'jotun vietnam',
        'nippon paint',
        'kova paint',
        'sika vietnam',
        'weber việt nam',
    ];
    $lc = mb_strtolower($title);
    foreach ($noise as $word) {
        if (mb_strpos($lc, $word) !== false && mb_strlen($lc) < 26) {
            return false;
        }
    }
    return true;
};

$stats = [
    'total' => 0,
    'updated' => 0,
    'skipped' => 0,
    'errors' => 0,
];

foreach ($rows as $row) {
    $stats['total']++;

    $product_id = isset($row['product_id']) ? (int) $row['product_id'] : 0;
    $slug = isset($row['slug']) ? sanitize_title((string) $row['slug']) : '';
    $brand = isset($row['brand']) ? sanitize_title((string) $row['brand']) : '';
    $local_file_rel = isset($row['local_file']) ? (string) $row['local_file'] : '';
    $page_url = isset($row['page_url']) ? esc_url_raw((string) $row['page_url']) : '';
    $image_url = isset($row['image_url']) ? esc_url_raw((string) $row['image_url']) : '';
    $official_title = isset($row['official_title']) ? trim((string) $row['official_title']) : '';

    if ($only_brand !== '' && $brand !== $only_brand) {
        $stats['skipped']++;
        continue;
    }

    if ($product_id <= 0 || $local_file_rel === '') {
        $stats['skipped']++;
        continue;
    }

    $product = wc_get_product($product_id);
    if (!$product instanceof WC_Product) {
        $stats['errors']++;
        continue;
    }

    $local_file_rel = ltrim(str_replace(['\\', '//'], '/', $local_file_rel), '/');
    $source_file = wp_normalize_path(trailingslashit($theme_root) . $local_file_rel);
    if (!file_exists($source_file)) {
        $stats['errors']++;
        continue;
    }

    $image_id = $import_local_image($source_file, $slug !== '' ? $slug : (string) $product_id);
    if ($image_id <= 0) {
        $stats['errors']++;
        continue;
    }

    if (!$dry_run) {
        set_post_thumbnail($product_id, $image_id);

        $alt_text = trim((string) $product->get_name());
        if ($alt_text !== '') {
            update_post_meta($image_id, '_wp_attachment_image_alt', $alt_text);
        }
        wp_update_post([
            'ID' => $image_id,
            'post_title' => $alt_text !== '' ? $alt_text : ('Product ' . $product_id),
        ]);

        if ($page_url !== '') {
            update_post_meta($product_id, '_official_source_page', $page_url);
        }
        if ($image_url !== '') {
            update_post_meta($product_id, '_official_source_image', $image_url);
        }
        update_post_meta($product_id, '_official_image_synced_at', gmdate('c'));
        update_post_meta($product_id, '_official_image_map_file', 'data/official_image_map.json');

        if ($apply_official_title && $looks_like_official_title($official_title)) {
            $current_name = trim((string) $product->get_name());
            if ($current_name !== $official_title) {
                $product->set_name($official_title);
                $product->save();
            }
        }
    }

    $stats['updated']++;
}

if (!$dry_run) {
    if (function_exists('my_theme_flush_product_cache_fragments')) {
        my_theme_flush_product_cache_fragments(0);
    }
    update_option('my_theme_filter_cache_version', (string) time(), false);
}

echo 'official_image_map_apply_done total=' . (int) $stats['total']
    . ' updated=' . (int) $stats['updated']
    . ' skipped=' . (int) $stats['skipped']
    . ' errors=' . (int) $stats['errors']
    . ' dry_run=' . ($dry_run ? 'yes' : 'no')
    . ' apply_official_title=' . ($apply_official_title ? 'yes' : 'no')
    . ' only_brand=' . ($only_brand !== '' ? $only_brand : 'all')
    . PHP_EOL;
